version: '3.5'

services:
  client:
    ports:
      - '3000:443'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  server:
    environment:
      - NODE_ENV=development
    env_file:
      - environment/db.dev.env
      - environment/constants.dev.env

  mongo:
    env_file:
      - environment/mongo.dev.env

  mongo-express:
    image: mongo-express
    ports:
      - 27018:8081
    env_file:
      - environment/mongo-express.dev.env
    restart: unless-stopped
