version: '3.5'

services:
  client:
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'

  server:
    environment:
      - NODE_ENV=production
    env_file:
      - environment/db.prod.env

  mongo:
    env_file:
      - environment/mongo.prod.env