version: '3.5'

services:
  client:
    build:
      context: ../client
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped

  server:
    image: node:8.12-alpine
    ports:
      - '3030:3030'
      - '8080:3030'
    command: yarn start
    working_dir: /app
    volumes:
      - '../api:/app'
    restart: unless-stopped

  mongo:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    restart: unless-stopped

volumes:
  db: ~
