version: '3.5'

services:
  client:
    build:
      context: ../client
      dockerfile: ./docker/Dockerfile
    ports:
      - '80:80'

  api:
    environment:
      - NODE_ENV=production
    env_file:
      - environment/db.prod.env

  mongo:
    env_file:
      - environment/mongo.prod.env